=== alvarogit-ops/pos-2026-tarefas/tarefa04/cardapio.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="PratoID">
    <xs:restriction base="xs:ID">
      <xs:pattern value="[pP][0-9]+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="cardapio">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="prato" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nome" type="xs:string"/>
              <xs:element name="descricao" type="xs:string"/>
              <xs:element name="ingredientes">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ingrediente" type="xs:string" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="preco" maxOccurs="unbounded">
                <xs:complexType mixed="true">
                  <xs:attribute name="moeda" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="calorias" type="xs:integer"/>
              <xs:element name="tempoPreparo" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="PratoID" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== alvarogit-ops/pos-2026-tarefas/tarefa04/cardapio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cardapio [
  <!ENTITY reais "R$">
]>
<cardapio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="cardapio.xsd">

  <prato id="p01">
    <nome>Pão Francês</nome>
    <descricao>Um pãozinho que muita gente come</descricao>
    <ingredientes>
      <ingrediente>Fermento</ingrediente>
      <ingrediente>Farinha</ingrediente>
    </ingredientes>
    <preco moeda="BRL">&reais;3,00</preco>
    <preco moeda="USD">USD 0,60</preco>
    <calorias>250</calorias>
    <tempoPreparo>3min</tempoPreparo>
  </prato>

  <prato id="p02">
    <nome>Bolo de Banana</nome>
    <descricao>Um bolo doce</descricao>
    <ingredientes>
      <ingrediente>banana</ingrediente>
      <ingrediente>farinha</ingrediente>
      <ingrediente>ovos</ingrediente>
    </ingredientes>
    <preco moeda="BRL">&reais;15,00</preco>
    <preco moeda="USD">USD 3,00</preco>
    <calorias>320</calorias>
    <tempoPreparo>45min</tempoPreparo>
  </prato>

  <prato id="p03">
    <nome>Café Expresso</nome>
    <descricao>Café pra aumentar o foco</descricao>
    <ingredientes>
      <ingrediente>Grãos de café</ingrediente>
      <ingrediente>água</ingrediente>
    </ingredientes>
    <preco moeda="BRL">&reais;6,00</preco>
    <preco moeda="USD">USD 1,20</preco>
    <calorias>5</calorias>
    <tempoPreparo>2min</tempoPreparo>
  </prato>

  <prato id="p04">
    <nome>Pão na Chapa</nome>
    <descricao>Pão de tradição mesmo</descricao>
    <ingredientes>
      <ingrediente>Pão francês</ingrediente>
      <ingrediente>Manteiga</ingrediente>
    </ingredientes>
    <preco moeda="BRL">&reais;5,00</preco>
    <preco moeda="USD">USD 1,00</preco>
    <calorias>310</calorias>
    <tempoPreparo>5min</tempoPreparo>
  </prato>

  <prato id="p05">
    <nome>Hambúrguer</nome>
    <descricao>Esse é o que muitos personagens fictícios gostam</descricao>
    <ingredientes>
      <ingrediente>Carne</ingrediente>
      <ingrediente>Queijo</ingrediente>
      <ingrediente>Pão</ingrediente>
      <ingrediente>Alface</ingrediente>
    </ingredientes>
    <preco moeda="BRL">&reais;25,00</preco>
    <preco moeda="USD">USD 5,00</preco>
    <calorias>550</calorias>
    <tempoPreparo>15min</tempoPreparo>
  </prato>

</cardapio>
